// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go

// Package rabbitmq is a generated GoMock package.
package rabbitmq

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	amqp091 "github.com/rabbitmq/amqp091-go"
)

// MockChannelProvider is a mock of ChannelProvider interface.
type MockChannelProvider struct {
	ctrl     *gomock.Controller
	recorder *MockChannelProviderMockRecorder
}

// MockChannelProviderMockRecorder is the mock recorder for MockChannelProvider.
type MockChannelProviderMockRecorder struct {
	mock *MockChannelProvider
}

// NewMockChannelProvider creates a new mock instance.
func NewMockChannelProvider(ctrl *gomock.Controller) *MockChannelProvider {
	mock := &MockChannelProvider{ctrl: ctrl}
	mock.recorder = &MockChannelProviderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockChannelProvider) EXPECT() *MockChannelProviderMockRecorder {
	return m.recorder
}

// GetChannel mocks base method.
func (m *MockChannelProvider) GetChannel() (*amqp091.Channel, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetChannel")
	ret0, _ := ret[0].(*amqp091.Channel)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetChannel indicates an expected call of GetChannel.
func (mr *MockChannelProviderMockRecorder) GetChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetChannel", reflect.TypeOf((*MockChannelProvider)(nil).GetChannel))
}
